name: nodejs
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]
jobs:
  build:
    uses: unional/.github/.github/workflows/typescript-build.yml@main
    secrets:
      codacy-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
  test:
    uses: unional/.github/.github/workflows/typescript-test.yml@main
    needs: build
  release:
    if: github.ref == 'refs/heads/main'
    uses: unional/.github/.github/workflows/npm-release.yml@main
    needs: test
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
